version: '2'
services:
  CouchDB:
    image: couchdb:2.1.1
    hostname: firetracker-couchdb
    stdin_open: true
    volumes:
      - firetracker-couchdb-settings:/opt/couchdb/etc/local.d
      - firetracker-couchdb-data:/opt/couchdb/data
    tty: true
    ports:
      - 5984:5984/tcp
  Application:
    build: .
    hostname: firetracker
    stdin_open: true
    tty: true
volumes:
  firetracker-couchdb-settings:
  firetracker-couchdb-data:

